"""Structural protocol for the pylitterbot robot interface used by Asher."""

from __future__ import annotations

from collections.abc import Callable
from datetime import datetime
from typing import Any, Protocol

from pylitterbot.activity import Activity
from pylitterbot.enums import LitterBoxStatus, NightLightMode


class RobotProtocol(Protocol):
    # ── identity ────────────────────────────────────────────────────────────
    @property
    def name(self) -> str: ...
    @property
    def serial(self) -> str: ...
    @property
    def model(self) -> str: ...

    # ── state ───────────────────────────────────────────────────────────────
    @property
    def is_online(self) -> bool: ...
    @property
    def status(self) -> LitterBoxStatus: ...
    @property
    def waste_drawer_level(self) -> float: ...
    @property
    def last_seen(self) -> datetime | None: ...
    @property
    def sleep_mode_enabled(self) -> bool: ...
    @property
    def panel_lock_enabled(self) -> bool: ...
    @property
    def night_light_mode_enabled(self) -> bool: ...

    # ── LR4+ optional state (absent on LR3 — access via getattr) ────────────
    @property
    def night_light_mode(self) -> NightLightMode | None: ...
    @property
    def night_light_brightness(self) -> int: ...
    @property
    def litter_level(self) -> float: ...
    @property
    def pet_weight(self) -> float: ...

    # ── methods ─────────────────────────────────────────────────────────────
    async def refresh(self) -> None: ...
    async def start_cleaning(self) -> bool: ...
    async def set_panel_lockout(self, value: bool) -> bool: ...
    async def set_sleep_mode(self, value: bool) -> bool: ...
    async def set_night_light_mode(self, mode: NightLightMode) -> bool: ...
    async def set_night_light_brightness(self, brightness: int) -> bool: ...
    async def get_activity_history(self, limit: int) -> list[Activity]: ...
    async def subscribe(self) -> None: ...
    async def unsubscribe(self) -> None: ...
    def on(self, event_name: str, callback: Callable[..., Any]) -> Callable[..., Any]: ...
